### ISSUE TITLE
Long duration throws error

### ISSUE THREAD

**Issue by craklyn** [FraBle/python-duckling#12]
Thanks for this very useful library. =]  And apologies in advance if this is simply a shortcoming in my understanding of my (limited) knowledge of Python, and not a problem with the library.

I am currently using python-duckling with the newest checkout of git.ai's duckling, which is duckling-0.4.23.jar.  I added weeks to python-duckling in the most straightforward way:

```
@@ -179,6 +179,7 @@ class Duckling(object):
             u'minute': self._parse_int,
             u'hour': self._parse_int,
             u'day': self._parse_int,
+            u'week': self._parse_int,
             u'month': self._parse_int,
```

After doing this, I ran on some transcribed conversations.  Because the transcriptions contain inaccuracies, I encountered the substring "7208 weeks".  This causes the following exception to be thrown:

```
>>> import duckling
>>> import pandas
>>> d = duckling.Duckling()
>>> d.load()
>>> print(d.parse("7208 weeks"))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\dblackburn\AppData\Local\Continuum\Anaconda3\lib\site-packages\duckling-1.3.2-py3.6.egg\duckling\duckling.py", line 135, in parse
    return self._parse_result(duckling_result)
  File "C:\Users\dblackburn\AppData\Local\Continuum\Anaconda3\lib\site-packages\duckling-1.3.2-py3.6.egg\duckling\duckling.py", line 166, in _parse_result
    field.getValue(), entry[u'dim'])
  File "C:\Users\dblackburn\AppData\Local\Continuum\Anaconda3\lib\site-packages\duckling-1.3.2-py3.6.egg\duckling\duckling.py", line 199, in _parse_dict
    result[key] = _functions_with_dim[key](field.getValue(), dim)
  File "C:\Users\dblackburn\AppData\Local\Continuum\Anaconda3\lib\site-packages\duckling-1.3.2-py3.6.egg\duckling\duckling.py", line 199, in _parse_dict
    result[key] = _functions_with_dim[key](field.getValue(), dim)
  File "C:\Users\dblackburn\AppData\Local\Continuum\Anaconda3\lib\site-packages\duckling-1.3.2-py3.6.egg\duckling\duckling.py", line 233, in _parse_value
    return _dims[dim](java_value)
  File "C:\Users\dblackburn\AppData\Local\Continuum\Anaconda3\lib\site-packages\duckling-1.3.2-py3.6.egg\duckling\duckling.py", line 211, in _parse_float
    return float(java_number.toString())
AttributeError: 'str' object has no attribute 'toString'
```

This runs fine with "1000 weeks".  The problem occurs due to integer overflow.

For now, I've worked around the problem with the following changes to _parse_float, but would appreciate any thoughts on whether this is a problem on my end, a problem with the library, or asking for 7208 weeks is simply an unreasonable input. =P

```
@@ -207,8 +208,11 @@ class Duckling(object):
         return result

     def _parse_float(self, java_number):
-        return float(java_number.toString())
-
+        if(hasattr(java_number, "toString")):
+            return float(java_number.toString())
+        else:
+            return "<<Absurdly large number>>"
```

**Comment by FraBle** [comment]
It seems to be a bug on in Duckling itself: https://github.com/wit-ai/duckling_old/issues/58
https://github.com/wit-ai/duckling_old/pull/165 added an exception handling to it.
You can find it in https://github.com/wit-ai/duckling_old/blob/master/src/duckling/time/api.clj#L60.

I'll check if I can add some more error handling around this.

**Comment by FraBle** [comment]
Printing out the error to the result, it would look like
```json
[
    {
        "body": "7208",
        "dim": "number",
        "end": 4,
        "start": 0,
        "value": {
            "type": "value",
            "value": 7208.0
        }
    },
    {
        "body": "7208 week",
        "dim": "duration",
        "end": 9,
        "start": 0,
        "value": {
            "normalized": {
                "unit": "second",
                "value": "Value cannot fit in an int: 4359398400"
            },
            "unit": "week",
            "value": 7208.0,
            "week": 7208
        }
    },
    {
        "body": "7208",
        "dim": "distance",
        "end": 4,
        "latent": true,
        "start": 0,
        "value": {
            "type": "value",
            "value": 7208.0
        }
    },
    {
        "body": "7208",
        "dim": "volume",
        "end": 4,
        "latent": true,
        "start": 0,
        "value": {
            "type": "value",
            "value": 7208.0
        }
    },
    {
        "body": "7208",
        "dim": "temperature",
        "end": 4,
        "latent": true,
        "start": 0,
        "value": {
            "type": "value",
            "value": 7208.0
        }
    },
    {
        "body": "7208",
        "dim": "time",
        "end": 4,
        "latent": true,
        "start": 0,
        "value": {
            "grain": "year",
            "type": "value",
            "value": "7208-01-01T00:00:00.000-08:00",
            "values": [
                {
                    "grain": "year",
                    "type": "value",
                    "value": "7208-01-01T00:00:00.000-08:00"
                }
            ]
        }
    }
]
```

**Comment by FraBle** [comment]
Error handling is now integrated. Check out version [1.5.1](https://pypi.python.org/pypi/duckling/1.5.1)

**Comment by craklyn** [comment]
Very cool.  Thanks for following up on this!

**Comment by FraBle** [comment]
You're welcome 😄
